### ISSUE TITLE
To integrate in another application

### ISSUE THREAD

**Issue by gauthampait** [zerodivisi0n/FinderMenu#8]
Hey

I tried the code and it works fine on my machine.
I few issues though. Can you please help ?

When I click on the Menu I want to get a callback to my application saying the item was clicked. I tried googling and I haven't found single way to do this :(

Will you also let me know how I can inject the code during my app launch and remove it during my app quit. Like how it works on dropbox ?

Please help.

Thank You
Gautham

@zerodivisi0n waiting for you reply.

**Comment by zerodivisi0n** [comment]
Hi!

When the menu is shown, method `finderWillShowContextMenu` of delegate `ILFinderMenuDelegate` invoked. So, the easiest way to do it is to subclass `ILSimpleMenuDelegate` or `ILPathMenuDelegate` and override method `finderWillShowContextMenu` to invoke superclass implementation, then do your stuff.

There are few ways to load menu in your application. The easiest, but ugly method to do it is by using helper _loader_ application with SUID-bit set. New and recommended way to do it is by using _ServiceManagement_ framework and `SMJobBless`. For example see [MachInjectSample](https://github.com/erwanb/MachInjectSample).

To remove the menu you need to restore overridden methods (see [ILFinderMenu](https://github.com/infinitelabs/FinderMenu/blob/master/FinderExt/ILFinderMenu.m#L60-L85)). I did not do it in my code, because it's just an example. I can try to add this to my code if it is still necessary.

**Comment by gauthampait** [comment]
I would like to Inject using the easiest way. Do you have any sample that I can because I will not be code signing my application to use SMJobBless.

Please help.

**Comment by zerodivisi0n** [comment]
The easiest way is to use `suid` bit ([wiki](http://en.wikipedia.org/wiki/Setuid)). You create separated _loader_ application, set it's owner to `root` and set `suid` bit on it. Then the application will run with `root` privileges and load your Finder extension.
**But this method is unsafe and not recommended to use at all.**
